import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { after, test } from "node:test";
import { assertInventory, expectedInventory, provenance, verifyChecksums } from "./release-integrity.mjs";

const roots = [];
after(() => roots.forEach((root) => rmSync(root, { recursive: true, force: true })));
function must(root, command, args) {
  const result = spawnSync(command, args, { cwd: root, encoding: "utf8" });
  assert.equal(result.status, 0, `${command} ${args.join(" ")}\n${result.stderr}${result.stdout}`);
  return result.stdout.trim();
}
function hash(value, algorithm = "sha256") { return createHash(algorithm).update(value).digest("hex"); }
const attributionFooter = "Generated by GPT-5 via Codex under supervision of @3leapsdave\n\nCo-Authored-By: GPT-5 <noreply@3leaps.net>\nRole: devlead\nCommitter-of-Record: @3leapsdave\n";

function provenanceFixture(commitMessage = "commit without attribution") {
  const root = mkdtempSync(join(tmpdir(), "sysprims-provenance-test-"));
  roots.push(root);
  mkdirSync(join(root, "docs/releases"), { recursive: true });
  writeFileSync(join(root, "VERSION"), "0.2.3\n");
  writeFileSync(join(root, "docs/releases/v0.2.3.json"), JSON.stringify({
    schema: "sysprims-release-plan/v1", version: "0.2.3", provenance_policy: "commit_footer",
    surfaces: { rust: { disposition: "publish" }, cli: { disposition: "publish" }, ffi: { disposition: "publish" }, go: { disposition: "publish", lock_phase: "resolved" }, typescript: { disposition: "publish", lock_phase: "resolved" } },
  }));
  must(root, "git", ["init", "-b", "main"]);
  must(root, "git", ["config", "user.name", "Fixture"]);
  must(root, "git", ["config", "user.email", "fixture@example.invalid"]);
  must(root, "git", ["add", "."]);
  must(root, "git", ["commit", "-m", commitMessage]);
  const commit = must(root, "git", ["rev-parse", "HEAD"]);
  const messages = join(root, "messages");
  mkdirSync(messages);
  const footer = `Release 0.2.3\n\n${attributionFooter}`;
  const tags = ["v0.2.3", "bindings/go/sysprims/v0.2.3"];
  for (const tag of tags) writeFileSync(join(messages, `${tag.replaceAll("/", "__")}.txt`), footer);
  const secret = join(root, "minisign.key");
  const pub = join(root, "minisign.pub");
  must(root, "minisign", ["-G", "-W", "-p", pub, "-s", secret]);
  const receiptPath = join(root, "receipt.json");
  const makeReceipt = (overrides = {}) => ({
    schema: "sysprims-release-provenance-exception/v1",
    version: "0.2.3",
    target_commit: commit,
    tags: tags.map((name) => ({ name, message_sha256: hash(footer) })),
    authorizing_maintainer: "@3leapsdave",
    decided_at: "2026-09-19T15:00:00Z",
    approval_reference: "durable-maintainer-receipt",
    ...overrides,
  });
  const sign = (receipt) => {
    writeFileSync(receiptPath, `${JSON.stringify(receipt, null, 2)}\n`);
    must(root, "minisign", ["-S", "-W", "-s", secret, "-m", receiptPath, "-x", `${receiptPath}.minisig`]);
  };
  return { root, pub, receiptPath, messages, tags, footer, makeReceipt, sign };
}

function withTagMessageEnv(fixture, operation) {
  const before = process.env.SYSPRIMS_TAG_MESSAGE_DIR;
  process.env.SYSPRIMS_TAG_MESSAGE_DIR = fixture.messages;
  try { return operation(); }
  finally {
    if (before === undefined) delete process.env.SYSPRIMS_TAG_MESSAGE_DIR;
    else process.env.SYSPRIMS_TAG_MESSAGE_DIR = before;
  }
}

function createFixtureTags(fixture, wrongTag) {
  const wrong = join(fixture.root, "wrong-tag-message.txt");
  writeFileSync(wrong, "wrong annotation bytes\n");
  for (const tag of fixture.tags) {
    const message = tag === wrongTag ? wrong : join(fixture.messages, `${tag.replaceAll("/", "__")}.txt`);
    must(fixture.root, "git", ["tag", "-a", tag, "--cleanup=verbatim", "-F", message]);
  }
}

function withReceiptEnv(fixture, operation) {
  const before = { receipt: process.env.SYSPRIMS_PROVENANCE_EXCEPTION_RECEIPT, pub: process.env.SYSPRIMS_PROVENANCE_EXCEPTION_PUBKEY, messages: process.env.SYSPRIMS_TAG_MESSAGE_DIR };
  process.env.SYSPRIMS_PROVENANCE_EXCEPTION_RECEIPT = fixture.receiptPath;
  process.env.SYSPRIMS_PROVENANCE_EXCEPTION_PUBKEY = fixture.pub;
  process.env.SYSPRIMS_TAG_MESSAGE_DIR = fixture.messages;
  try { return operation(); }
  finally {
    for (const [key, value] of Object.entries({ SYSPRIMS_PROVENANCE_EXCEPTION_RECEIPT: before.receipt, SYSPRIMS_PROVENANCE_EXCEPTION_PUBKEY: before.pub, SYSPRIMS_TAG_MESSAGE_DIR: before.messages })) {
      if (value === undefined) delete process.env[key]; else process.env[key] = value;
    }
  }
}

test("signed provenance receipt accepts exact version, commit, tag set, and message bytes", () => {
  const fixture = provenanceFixture(); fixture.sign(fixture.makeReceipt());
  withReceiptEnv(fixture, () => assert.doesNotThrow(() => provenance(fixture.root, "0.2.3")));
});

for (const [name, overrides, pattern] of [
  ["wrong version", { version: "0.2.2" }, /version mismatch/],
  ["wrong commit", { target_commit: "b".repeat(40) }, /target commit mismatch/],
  ["incomplete tags", { tags: [{ name: "v0.2.3", message_sha256: "a".repeat(64) }] }, /tag set mismatch/],
  ["wrong message hash", { tags: [{ name: "v0.2.3", message_sha256: "a".repeat(64) }, { name: "bindings/go/sysprims/v0.2.3", message_sha256: "a".repeat(64) }] }, /hash mismatch/],
]) {
  test(`provenance receipt rejects ${name}`, () => {
    const fixture = provenanceFixture(); fixture.sign(fixture.makeReceipt(overrides));
    withReceiptEnv(fixture, () => assert.throws(() => provenance(fixture.root, "0.2.3"), pattern));
  });
}

test("provenance receipt rejects a bad signature and generic override", () => {
  const fixture = provenanceFixture(); fixture.sign(fixture.makeReceipt());
  writeFileSync(`${fixture.receiptPath}.minisig`, "forged\n");
  process.env.SYSPRIMS_ALLOW_PROVENANCE_EXCEPTION = "1";
  try { withReceiptEnv(fixture, () => assert.throws(() => provenance(fixture.root, "0.2.3"), /minisign/)); }
  finally { delete process.env.SYSPRIMS_ALLOW_PROVENANCE_EXCEPTION; }
});

test("complete commit footer binds both stored tag messages to the intended bytes", () => {
  const fixture = provenanceFixture(`release commit\n\n${attributionFooter}`);
  createFixtureTags(fixture);
  withTagMessageEnv(fixture, () => assert.doesNotThrow(() => provenance(fixture.root, "0.2.3")));
});

for (const tag of ["v0.2.3", "bindings/go/sysprims/v0.2.3"]) {
  test(`complete commit footer rejects wrong annotation content for ${tag}`, () => {
    const fixture = provenanceFixture(`release commit\n\n${attributionFooter}`);
    createFixtureTags(fixture, tag);
    withTagMessageEnv(fixture, () => assert.throws(
      () => provenance(fixture.root, "0.2.3"),
      new RegExp(`intended bytes for ${tag.replaceAll("/", "\\/")}`),
    ));
  });
}

test("commit footer rejects a non-policy coauthor email", () => {
  const wrongFooter = attributionFooter.replace("noreply@3leaps.net", "model@example.invalid");
  const fixture = provenanceFixture(`release commit\n\n${wrongFooter}`);
  assert.throws(() => provenance(fixture.root, "0.2.3"), /complete attribution footer is missing/);
});

test("phase inventory and checksum manifests reject leftovers and wrong hashes", () => {
  const root = mkdtempSync(join(tmpdir(), "sysprims-inventory-test-")); roots.push(root);
  const { base } = expectedInventory("0.2.3");
  for (const name of base) writeFileSync(join(root, name), `${name}\n`);
  const manifest = (algorithm) => base.map((name) => `${hash(Buffer.from(`${name}\n`), algorithm)}  ${name}`).join("\n") + "\n";
  writeFileSync(join(root, "SHA256SUMS"), manifest("sha256"));
  writeFileSync(join(root, "SHA512SUMS"), manifest("sha512"));
  assert.doesNotThrow(() => verifyChecksums(root, base));
  assert.doesNotThrow(() => assertInventory(root, [...base, "SHA256SUMS", "SHA512SUMS"].sort(), "checksummed"));
  writeFileSync(join(root, "leftover-v9.9.9.zip"), "foreign\n");
  assert.throws(() => assertInventory(root, [...base, "SHA256SUMS", "SHA512SUMS"].sort(), "checksummed"), /extra=.*leftover/);
  rmSync(join(root, "leftover-v9.9.9.zip"));
  writeFileSync(join(root, base[0]), "changed\n");
  assert.throws(() => verifyChecksums(root, base), /digest mismatch/);
});

test("release leaves are guard-wired and only release-publish can undraft", () => {
  const makefile = readFileSync("Makefile", "utf8");
  assert.match(makefile, /^release-download: release-guard-tag-version-post release-guard-provenance/m);
  assert.match(makefile, /^release-checksums: release-guard-downloaded/m);
  assert.match(makefile, /^release-sign: release-require-checksummed/m);
  assert.match(makefile, /^release-upload: release-guard-tag-version-post release-guard-provenance release-guard-signed/m);
  assert.match(makefile, /^release-publish: release-guard-tag-version-post release-guard-provenance release-guard-remote/m);
  const upload = readFileSync("scripts/upload-release-assets.sh", "utf8");
  assert.doesNotMatch(upload, /--draft=false/);
  const implementation = readFileSync("scripts/release-integrity.mjs", "utf8");
  assert.equal((implementation.match(/--draft=false/g) ?? []).length, 1);
});

test("npm dry-run cannot enter the protected OIDC job", () => {
  const workflow = readFileSync(".github/workflows/typescript-npm-publish.yml", "utf8");
  assert.match(workflow, /publish:\n[\s\S]*?if: \$\{\{ !inputs\.dry_run \}\}[\s\S]*?environment: publish-npm/);
  const stageBlock = workflow.slice(workflow.indexOf("  stage:"), workflow.indexOf("  publish:"));
  assert.doesNotMatch(stageBlock, /environment:|id-token:/);
});
